version: "3"
services:
  frontend:
    image: capstone-frontend
    environment:
      REACT_APP_AWS_ACCESSKEY: $REACT_APP_AWS_ACCESSKEY
      REACT_APP_AWS_SECRETKEY: $REACT_APP_AWS_SECRETKEY
      REACT_APP_S3_NAME: $REACT_APP_S3_NAME
      REACT_APP_S3_REGION: $REACT_APP_S3_REGION
      REACT_APP_API_URL: "http://localhost:8080/feed"
    ports: 
      - 3000:3000
  backend:
    image: capstone-backend
    environment:
      PORT: 8080
      ENVIRONMENT: $ENVIRONMENT
      DB_HOST: $DB_HOST
      DB_USER: $DB_USER
      DB_PASSWORD: $DB_PASSWORD
      DB: $DB
    ports:
      - 8080:8080

