apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: frontend
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      service: frontend
  template:
    metadata:
      labels:
        service: frontend
        api: external
    spec:
      containers:
        - image: eperuza/capstone-frontend:v1
          name: frontend
          imagePullPolicy: Always
          env:
            - name: REACT_APP_API_URL
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REACT_APP_API_URL
            - name: REACT_APP_S3_NAME
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REACT_APP_S3_NAME
            - name: REACT_APP_S3_REGION
              valueFrom:
                configMapKeyRef:
                  name: env-config
                  key: REACT_APP_S3_REGION
            - name: REACT_APP_AWS_ACCESSKEY
              valueFrom: 
                secretKeyRef:
                  name: env-secret
                  key: REACT_APP_AWS_ACCESSKEY
            - name: REACT_APP_AWS_SECRETKEY
              valueFrom: 
                secretKeyRef:
                  name: env-secret
                  key: REACT_APP_AWS_SECRETKEY
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "64Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      restartPolicy: Always